server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
aptiv:
  smb:
#    hostname: localhost
#    username: zhou.li@aptiv.com
#    password: liudalin19950104!
#    root-folder: 新建文件夹
    hostname: 10.132.15.18
    username: zhou.li@aptiv.com
    password: liudalin19950104!
    root-folder: K426 ArchivingFiles

